#### Numpy

- Pandas : https://pandas.pydata.org/
- Numpy : https://numpy.org/
- 수치해석, 수학적 처리, 통계 등을 위한 라이브러리(모듈) - Scipy, Pandas, Matploplib

##### Numpy 설치
```python
!pip install numpy
```

In [1]:
# 현재 버전확인
!pip list

Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
colorama          0.4.6
comm              0.1.3
contourpy         1.1.0
cycler            0.11.0
debugpy           1.6.7
decorator         5.1.1
et-xmlfile        1.1.0
executing         1.2.0
Faker             18.11.1
fonttools         4.40.0
ipykernel         6.23.2
ipython           8.14.0
jedi              0.18.2
Jinja2            3.1.2
jupyter_client    8.2.0
jupyter_core      5.3.1
kiwisolver        1.4.4
MarkupSafe        2.1.3
matplotlib        3.7.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.6
numpy             1.25.0
openpyxl          3.1.2
packaging         23.1
pandas            2.0.2
parso             0.8.3
pickleshare       0.7.5
Pillow            9.5.0
pip               23.1.2
platformdirs      3.7.0
prompt-toolkit    3.0.38
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.15.1
PyMySQL           1.0.3
pyparsing         3.1.0
python-dateutil   2.8.2
py

In [3]:
!pip install numpy

In [4]:
!pip install pandas

In [5]:
# import 
import pandas as pd
import numpy as np

##### numpy를 쓰는 이유
- python 리스트를 만들고 사용처리(1,000,000건) - 대략 200ms
- numpy 배열을 만들고 처리하는데(1,000,000건) - 대략 20ms (10배정도 빠름)

In [9]:
py_list = list(range(1_000_000)) # 100만건 리스트 만들기

In [10]:
np_arr = np.arange(1_000_000)

In [11]:
## 파이썬 리스트 사용
%timeit for _ in range(10): py_list2 = py_list * 2

167 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
## 넘파이로 리스트 사용
%timeit for _ in range(10): np_arr2 = np_arr * 2

16 ms ± 412 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### 넘파이로 배열 생성, 연산 등

- 파이썬 리스트는 +(리스트끼리), *(숫자만) 연산 밖에 없음
- 행렬(벡터)로 연산을 하고 싶으면 numpy 배열로 형변환 후에 처리할 것

In [20]:
# 1차원 배열생성
np_arr1 = np.array([1, 3, 5])
np_arr1

array([1, 3, 5])

In [30]:
# 2차원 배열
np_arr2 = np.array([[1, 3, 5],  [1, 3, 5]])
np_arr2

array([[1, 3, 5],
       [1, 3, 5]])

In [22]:
# 3차원 배열
np_arr3 = np.array([[[0, 2, 4],  [8, 10, 12]], [[1, 3, 5],  [7, 9, 12]]])
np_arr3

array([[[ 0,  2,  4],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 12]]])

In [27]:
# 파이썬 기본 리스트(배열)
list1 = [1, 3, 5]
list1

[1, 3, 5]

In [28]:
# [1, 3, 5],  [1, 3, 5] 는 튜플로 1차원 배열이 두개 만들어짐 -> numpy에서는 허용안됨
# [[1, 3, 5],  [1, 3, 5]] 2차원 배열
list2 = [[1, 3, 5],  [1, 3, 5]]
list2

[[1, 3, 5], [1, 3, 5]]

In [33]:
# 길의 4의 1차원 배열을 전부 0으로 채울것
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [34]:
np_arr5 = np.zeros([2, 3])
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np_arr6 = np.empty([2, 3])
np_arr6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# 랜덤은 활용도 있음
np.random.randn(2, 3)

array([[-0.10333139,  0.32206125,  0.86383896],
       [ 0.63406801, -0.19133734, -1.65638297]])

In [47]:
np_arr7 = np.arange(10)
np_arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# 파이썬에서 리스트만든 다음에 numpy형태의 배열로 변경
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# 연산
np_arr7 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
# 파이썬 리스트는 +(리스트끼리), *(숫자만)

In [49]:
np_arr7 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [50]:
np_arr7 / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [51]:
np_arr7 // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [59]:
# numpy 배열은 +더하기 연산
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
# 파이썬 리스트 + concat(두 리스트를 합침)
list(range(10)) + list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
# 비교연산
(np_arr7 + np_arr7) < 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [54]:
(np_arr7 + np_arr7) != 10

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [67]:
# 조회
np_arr7[1]

1

In [69]:
# 인덱스 크기를 벗어나면 IndexError 예외발생
np_arr7[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [70]:
np_arr7[np_arr7 < 5]

array([0, 1, 2, 3, 4])

In [74]:
list2 = list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
[x for x in range(10) if x < 5] # 리스트 내포

[0, 1, 2, 3, 4]

In [79]:
np_arr7[3:9] # 뒤에 인덱스는 항상 -1

array([3, 4, 5, 6, 7, 8])

In [81]:
# 2차원 배열에서 값 조회
np_arr2[1][2]

5

In [87]:
np_arr2[1, 2] = 9
np_arr2

array([[1, 3, 5],
       [1, 3, 9]])

In [86]:
# 값 변경(치환)
np_arr7[np_arr7 < 5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

##### 속성
- shape, dtype, T

In [92]:
# 1차원
np_arr1.shape

(3,)

In [93]:
# 2차원
np_arr2.shape

(2, 3)

In [94]:
np_arr2.dtype

dtype('int32')

In [95]:
# Pivot
np_arr2.T

array([[1, 1],
       [3, 3],
       [5, 9]])

In [96]:
np_arr2.T.shape

(3, 2)

##### 기타 함수

In [98]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np_arr8.mean()

4.5

In [101]:
np_arr8.sum()

45

In [102]:
np_arr8.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [103]:
np_arr9 = np.random.randn(10)
np_arr9

array([ 0.73885594,  0.41500593,  0.21249792,  0.10537649,  1.46434683,
        1.03378733, -1.57378382, -0.1613436 , -0.2472037 , -1.41455512])

In [107]:
# 오름차순 정렬
np_arr9.sort()

In [108]:
np_arr9

array([-1.57378382, -1.41455512, -0.2472037 , -0.1613436 ,  0.10537649,
        0.21249792,  0.41500593,  0.73885594,  1.03378733,  1.46434683])

In [109]:
# 내림차순 정렬
-np.sort(-np_arr9)

array([ 1.46434683,  1.03378733,  0.73885594,  0.41500593,  0.21249792,
        0.10537649, -0.1613436 , -0.2472037 , -1.41455512, -1.57378382])

##### 테스트용 데이터프레임 예제

In [122]:
# 테스트용 더미데이터프레임 만들기
# 판다스와 조합해서 생성
size = 10
df = pd.DataFrame({
    'class': [['A', 'B', 'C', 'D', 'F'][np.random.randint(0, 5)] for i in range(0, size)],
    'year': [np.random.randint(2010, 2024) for i in range(0, size)],
    'month': [np.random.randint(1, 13) for i in range(0, size)],
    'val1': [np.random.randint(1, 11) for i in range(0, size)],
    'val2': [np.random.randint(100, 1000) for i in range(0, size)],
    'val3': [np.random.randint(10000, 20000) for i in range(0, size)]
})

df

class  year  month  val1  val2   val3
0     A  2019      6     3   318  19723
1     C  2013      5    10   274  10869
2     B  2020     12     5   152  13227
3     A  2018     10     6   691  16876
4     F  2016      2     3   741  19280
5     C  2013      5     6   648  11068
6     F  2022     10     7   566  17683
7     C  2018     11     7   813  13768
8     C  2023      9     3   973  19217
9     F  2015      3     6   402  18677

In [123]:
df.shape    

(10, 6)

In [124]:
df.dtypes

class    object
year      int64
month     int64
val1      int64
val2      int64
val3      int64
dtype: object

In [127]:
df.T

0      1      2      3      4      5      6      7      8      9
class      A      C      B      A      F      C      F      C      C      F
year    2019   2013   2020   2018   2016   2013   2022   2018   2023   2015
month      6      5     12     10      2      5     10     11      9      3
val1       3     10      5      6      3      6      7      7      3      6
val2     318    274    152    691    741    648    566    813    973    402
val3   19723  10869  13227  16876  19280  11068  17683  13768  19217  18677