# 1일차
- 빅데이터 개발환경
    - Python 64bit
    - VisualStudio Code, Anaconda, Colab, etc 
    - Database | OpenAPI | WebCrawling

- 빅데이터용 파이썬 학습
    - 생략

- 데이터 분석용 파이썬 실습
    - 데이터 입출력 부터

## 마크다운 활용

### 이미지부터 표까지
- 깃허브 README.md와 동일하게 사용할 것!
    - 아래 예제

### 이미지 추가

> **인용** 좀 하세요~ 제발

<img src="https://dojang.io/pluginfile.php/14085/mod_page/content/7/046011_.png" width="400">

<img src="https://raw.githubusercontent.com/hugoMGSung/pknu_aspnet_2023/main/images/restapi02.gif" width="400">


---

|제목|내용|비고|
|:-----|----------:|:----:|
|제목1|내용1|비고1|
|제목2|내용2|비고2|
|제목3|내용3|비고3|
|제목4|내용입니다4|비고4|
|제목입니다.|내용4|비고4예용|

## 주피터 노트북 디버깅

- 브레이크 포인트(중단점 클릭)
- Ctrl + Shift + Alt + Enter
    - py 디버깅과 동일(F10, F11) 사용

## 데이터 입출력

### 기본 출력

In [1]:
## 최종하나면 출력
'Hello Python.'
print('Hello Python!')

Hello Python!


In [2]:
## 여러개 출력 안됨
'Hello BigData'
'Hello BigData!'
'Hello BigData~~!!'

'Hello BigData~~!!'

In [3]:
## 여러개 출력하고 싶으면 print() 사용
print('Hello BigData')
print('Hello BigData!')
print('Hello BigData~~!!')

Hello BigData
Hello BigData!
Hello BigData~~!!


## 입출력 이전

### 데이터 분석용 라이브러리 리스트
- 공부해야할 것들 기본
    - Pandas
    - openpyxl (import 필요없음)
    - Numpy
    - Matplotlib
    - folium

- 추가로 공부해야할 것들
    - Seaborn
    - tqdm
    - wordcloud
    - ...

- 머신러닝, 딥러닝으로 가면??
    - SckitLearn
    - Tensorflow
    - PyTorch
    - ...

### 데이터 가져오기

- 주피터 노트북에서 데이터 가져올 때는 무조건 판다스 사용!
    - 나머지는 쓰기 까다로움

#### 기본
- Pandas
    - 받는 데이터는 기본이 DataFrame임, 따라서 변수명을 df_로 진행(하위 시리즈는 옵션)
    - 시작!

In [4]:
## 없으면 !pip install pandas
import pandas as pd

## URL 인코딩 파싱용 추가
from urllib import parse

In [5]:
## 웹사이트 URL에 있는 한글은 URL인코딩할 것!
file_name = 'https://raw.githubusercontent.com/hugoMGSung/bigdata-python-2023/main/Day03/' + parse.quote('충청북도_푸드뱅크현황.csv')
file_name

'https://raw.githubusercontent.com/hugoMGSung/bigdata-python-2023/main/Day03/%EC%B6%A9%EC%B2%AD%EB%B6%81%EB%8F%84_%ED%91%B8%EB%93%9C%EB%B1%85%ED%81%AC%ED%98%84%ED%99%A9.csv'

In [6]:
## csv는 UTF-8 인코딩 필수는 아니지만 속성 지정할 것!
df_basic = pd.read_csv(filepath_or_buffer=file_name, encoding='UTF-8')
df_basic.head()

지역           시군구 센터단위  센터구분         지원센터  신고구분           운영단체명 운영법인분류(대)  \
0  충북  충청북도 청주시 흥덕구   광역  푸드뱅크  광역기부식품등지원센터  당연신고     충청북도사회복지협의회     법인 운영   
1  충북  충청북도 청주시 흥덕구   기초  푸드뱅크    청주시흥덕푸드뱅크  임의신고      청주시사회복지협의회     법인 운영   
2  충북  충청북도 청주시 상당구   기초  푸드뱅크    청주구세군푸드뱅크  당연신고       구세군청주복지센터     법인 운영   
3  충북  충청북도 청주시 흥덕구   기초  푸드뱅크   청주사랑나눔푸드뱅크  당연신고              개인     개인 운영   
4  충북  충청북도 청주시 청원구   기초  푸드뱅크     청주드림푸드뱅크  당연신고  기독교대한감리회(드림교회)     법인 운영   

  대표자명        센터전화번호                             주소        등록일자  
0  김*석  043-234-1377           청주시 흥덕구 공단로 87, 302호  2000-05-18  
1  이*형  043-267-1377      청주시 흥덕구 무심서로 665(운천동), 2층  2002-08-19  
2  이*혁  043-254-1377  청주시 상당구 쇠내로 145번길 15, A동 202호  2010-01-01  
3  조*옥  043-266-1377          청주시 흥덕구 강서로 71번길 20-3  2008-03-03  
4  문*길  043-218-7991     청주시 청원구 상리로17번길 27-40(율량동)  2012-05-14

In [7]:
## 깃헙 기본링크 주소는 안됨
file_path = 'https://github.com/hugoMGSung/bigdata-analysis-2023/blob/main/Datas/university_list_2020.xlsx'
df_excel = pd.read_excel(file_path)
df_excel

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [ ]:
## raw.githubusercontent.com 으로 변경할 것!!
## sheet_name과 header, skiprows, skipfooter 활용 필요!
file_path = 'https://raw.githubusercontent.com/hugoMGSung/bigdata-analysis-2023/main/Datas/university_list_2020.xlsx'
df_excel = pd.read_excel(file_path, sheet_name='대학원', header=5)
df_excel.head()

연도   학교종류  시도      행정구           학교명  \
0  2020  일반대학원  서울   서울 서초구  가톨릭대학교 일반대학원   
1  2020  일반대학원  서울   서울 종로구  가톨릭대학교 일반대학원   
2  2020  일반대학원  서울  서울 서대문구   감리교신학대학교대학원   
3  2020  일반대학원  서울   서울 광진구    건국대학교일반대학원   
4  2020  일반대학원  서울  서울 서대문구   경기대학교 일반대학원   

                                            학교명(영문)    본분교 학교상태  설립  우편번호  \
0  Graduate School The Catholic University of Korea  제2캠퍼스   기존  사립  6591   
1  Graduate School The Catholic University of Korea  제3캠퍼스   기존  사립  3083   
2                     The Graduate School of M.T.U.     본교   기존  사립  3745   
3                 KONKUK UNIVERSITY GRADUATE SCHOOL     본교   기존  사립  5029   
4             GRADUATE SCHOOL OF KYONGGI UNIVERSITY     본교   기존  사립  3746   

                                        주소                  전화번호  \
0    서울특별시 서초구 반포대로 222 (반포동, 가톨릭대학교 성모병원)  02-2258-7114           
1  서울특별시 종로구 창경궁로 296-12 (혜화동, 가톨릭대학교성신교정)  02-740-9714            
2        서울특별시 서대문구 독립문로 56 (냉천동, 감리교신학대학)  02-361-9114            
3           서울특별시 광진구 능동로 120 (화양동, 건국대학교)           02-450-3263   
4      서울특별시 서대문구 경기대로9길 24 (충정로2가, 경기대학교)  02-390-5242            

                   팩스번호                           홈페이지  
0  02-2258-7742          songeui.catholic.ac.kr/gscuk/  
1  02-741-2801                      www.catholic.ac.kr  
2  02-361-9299                           www.mtu.ac.kr  
3           02-452-6490              grad.konkuk.ac.kr  
4  02-313-4131             www.kyonggi.ac.kr/kgraduate

#### Database
- DB 종류별 VS code extension
    - SQLServer : SQL Server (msssql) {Microsoft}
    - Oracle : Oracle Developer Tools for VSCode {Oracle}
    - MySQL : MySQL {Jun Han}

#### MySQL
- pymysql 설치

In [ ]:
!pip install pymysql

In [ ]:
import pymysql

In [ ]:
## 테스트
conn = pymysql.connect(host='210.119.12.52', port=3306, user='root', passwd='12345', db='bookrentalshop')
query = 'SELECT * FROM bookstbl'

df_books = pd.read_sql_query(sql=query, con=conn, index_col='bookIdx')
df_books.head()

C:\Users\perso\AppData\Local\Temp\ipykernel_29124\4062082495.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_books = pd.read_sql_query(sql=query, con=conn, index_col='bookIdx')


Author Division            Names ReleaseDate           ISBN  \
bookIdx                                                                  
1        넬레 노이하우스     B001     잔혹한 어머니의 날 1  2019-10-07  9791158791179   
2        넬레 노이하우스     B001     잔혹한 어머니의 날 2  2019-10-07  9791158791186   
3         매뉴 라인하트     B006  월드 오브 워크래프트 팝업북  2019-10-21  9788959527779   
4            묵향동후     B003           마도조사 2  2019-09-03  9791127852122   
5         오코제키 다이     B005            루팡의 딸  2019-09-25  9788998274412   

           Price  
bookIdx           
1        11520.0  
2        11520.0  
3        52200.0  
4        12600.0  
5        13500.0

### 데이터 내보내기

In [ ]:
## to_csv, to_excel 함수등 활용
df_books.to_csv('../Datas/export_bookrentalshop.csv', encoding='UTF-8', index=True)

In [ ]:
df_books.to_excel('../Datas/export_bookrentalshop.xlsx')

## 라이브러리 맛보기

-  기본
    - ~~Pandas~~
    - ~~openpyxl~~
    - Numpy : NumPy는 과학 컴퓨팅을 위한 기본 패키지
    - Matplotlib
    - folium

### Numpy

#### 기본 사용법
- 넘파이 타입
    - 불린형 : np.bool_
    - 정수형 : np.int8, np.int16, np.int32, np.int64
    - 실수형 : np.float32, np.float64
    - 복소수 : np.complex64, np.complex128

- 추가
    - np.nan : not a number. Null, None과 유사(완전 일치X)
    - np.inf : infinite 무한대

In [ ]:
## Numpy import
import numpy as np

### 핵심

NumPy와 패키지의 핵심은 ndarray(배열) 객체

In [ ]:
## 1차원
a1 = np.array((0.1, 0.2, 0.3))
a1

array([0.1, 0.2, 0.3])

In [ ]:
a1.shape

(3,)

In [ ]:
a1.dtype

dtype('float64')

In [ ]:
a2 = np.array(((1,2,3), (4,5,6)))
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.dtype

dtype('int32')

In [ ]:
ae2 = np.zeros((3, 3))
ae2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ae2 = np.ones((3,3), dtype='float64')
ae2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ae2 = np.empty((3, 3))
ae2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 인덱스, 불린배열, 합치기 등

In [ ]:
## 인덱싱
ax = np.array([1.2, -1.5, 2, 5.4, 6.7])
ax

array([ 1.2, -1.5,  2. ,  5.4,  6.7])

In [ ]:
ax.dtype

dtype('float64')

In [ ]:
ax[0]

1.2

In [ ]:
ax[2]

2.0

In [ ]:
ax[0:3]

array([ 1.2, -1.5,  2. ])

In [ ]:
ax[-2]

5.4

In [ ]:
## 불린 배열
ax[ax > 1.5]

array([2. , 5.4, 6.7])

In [ ]:
ay = np.array([1.2, 1.3, 2.2, 0, 3.6, 0])
np.nonzero(ay)

(array([0, 1, 2, 4], dtype=int64),)

In [ ]:
## 합치기
aa = np.array([[1,2],[3,4]])
ab = np.array([[5,6]])

np.concatenate((aa, ab), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((aa, ab.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
ac = np.array([1,2,3])
ad = np.array([4,5,6])
np.vstack((ac, ad))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
## np.append(ac, ad) 와 동일
np.hstack((ac, ad)) 

array([1, 2, 3, 4, 5, 6])

#### 연산

- 사칙연산 모두 가능 (파이썬 배열과 차이)

#### 이진탐색

![이진탐색](https://wikidocs.net/images/page/14597/11.png)

In [ ]:
az = np.array([0., 13., 26., 30.])

print(az)
print(-1,':',np.searchsorted(az,-1.),',',np.searchsorted(az,-1.,side='right'))
print( 0,':',np.searchsorted(az, 0.),',',np.searchsorted(az, 0.,side='right'))
print( 5,':',np.searchsorted(az, 5.),',',np.searchsorted(az, 5.,side='right'))
print(13,':',np.searchsorted(az,13.),',',np.searchsorted(az,13.,side='right'))
print(15,':',np.searchsorted(az,15.),',',np.searchsorted(az,15.,side='right'))
print(30,':',np.searchsorted(az,30.),',',np.searchsorted(az,30.,side='right'))
print(35,':',np.searchsorted(az,35.),',',np.searchsorted(az,35.,side='right'))

[ 0. 13. 26. 30.]
-1 : 0 , 0
0 : 0 , 1
5 : 1 , 1
13 : 1 , 2
15 : 2 , 2
30 : 3 , 4
35 : 4 , 4


#### 복사

In [ ]:
lf = [1, 2, 3]
af = np.array(lf)
af

array([1, 2, 3])

In [ ]:
## 얕은 복사(shallow copy)
ah = af
ah

array([20,  2,  3])

In [ ]:
ah[0] = 20
ah

array([20,  2,  3])

In [ ]:
af

array([20,  2,  3])

In [ ]:
ah is af

True

In [ ]:
## 깊은 복사(deep copy)
ai = af.copy()

In [ ]:
ai[0] = 30
af

array([20,  2,  3])

In [ ]:
ai is af

False

#### Numpy IO

넘파이에서 파일 읽고 쓰기

In [ ]:
## 파일쓰기
np.savetxt('../Datas/random_array.txt', ax)

In [ ]:
## 파일읽기
flax = np.loadtxt('../Datas/random_array.txt')
flax

array([ 1.2, -1.5,  2. ,  5.4,  6.7])

In [ ]:
## 백업
ax.tofile('backup')

In [ ]:
## 복구
bax = np.fromfile('backup')
bax

array([ 1.2, -1.5,  2. ,  5.4,  6.7])