## 라이브러리 맛보기

https://wikidocs.net/book/1704 참조

-  기본
    - ~~Pandas~~
    - ~~openpyxl~~
    - ~~Numpy~~
    - Matplotlib
    - folium

### Scipy
- 과학기술계산을 위한 Python 라이브러리
    - NumPy, Matplotlib, pandas, SymPy와 연계되어 있음

#### 기본 사용법

In [1]:
!pip install scipy

In [2]:
## Numpy and Scipy
import numpy
import scipy

In [3]:
numpy.show_config()

openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFI

In [4]:
scipy.show_config()

{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.33",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.12.1",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-tkj0pjht\\overlay\\Lib\\site-packages\\pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  

c:\DEV\LANGS\Python\Python311\Lib\site-packages\scipy\__config__.py:140: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 계산속도
- 계산속도
    - CPU time : 작업을 수행한 프로세서의 시간을 합산한 시간. time.process_time()에서 리턴된 값의 차이로 계산
    - wall time : 작업을 수행한 시간. time.perf_counter()이나 time.time()에서 리턴되는 값의 차이. time_perf_counter()가 보다 정확한 값을 제시

In [10]:
## 시간속도 체크
import time
import numpy as np
import scipy.linalg as linalg

A = np.random.random(size=(10000,10000))

cpuTime   = time.process_time()    # CPU time
wallTime1 = time.perf_counter()   # wall time
wallTime2 = time.time()            # wall time

linalg.norm(A)

cpuTime   = time.process_time() - cpuTime     # CPU time
wallTime1 = time.perf_counter() - wallTime1   # wall time
wallTime2 = time.time() - wallTime2           # wall time

print('cpuTime : ', cpuTime)
print('wallTime1 : ', wallTime1)
print('wallTime2 : ', wallTime2)

cpuTime :  0.40625
wallTime1 :  0.17138130002422258
wallTime2 :  0.1719954013824463


#### 선형대수

#### 행렬곱

In [15]:
A = np.array([[1,2,-1],
              [2,7,4],
              [0,4,-1]])

b = np.array([1,0,1.2])

# 행결 벡터 곱셈
y1 = np.matmul(A,b)
y2 = np.dot(A,b)
y3 = A.dot(b)

# 행령 행렬 곱셈
B = np.array([[1,2,3,4],
              [-1,2,3,1],
              [3,-2,5,9]])

C1 = np.matmul(A,B)
C2 = np.dot(A,B)
C3 = A.dot(B)

In [12]:
C1

array([[-4,  8,  4, -3],
       [ 7, 10, 47, 51],
       [-7, 10,  7, -5]])

In [13]:
C2

array([[-4,  8,  4, -3],
       [ 7, 10, 47, 51],
       [-7, 10,  7, -5]])

In [14]:
C3

array([[-4,  8,  4, -3],
       [ 7, 10, 47, 51],
       [-7, 10,  7, -5]])

...